import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";import {fileURLToPath} from "node:url";import {spawnSync} from "node:child_process";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const validator=path.join(root,"scripts/validate-radar.mjs");const base=JSON.parse(fs.readFileSync(path.join(root,"collection-template.json"),"utf8"));
const run=o=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"radar-v5-"));const file=path.join(dir,"case.json");fs.writeFileSync(file,JSON.stringify(o));return spawnSync(process.execPath,[validator,file],{encoding:"utf8"})};
test("empty pre-audit template validates",()=>assert.equal(run(structuredClone(base)).status,0));
test("registry contains 10-20 broad sources",()=>{const r=JSON.parse(fs.readFileSync(path.join(root,"source-registry.json")));assert.ok(r.sources.length>=10&&r.sources.length<=20);assert.ok(new Set(r.sources.map(x=>x.family)).size>=5)});
test("required non-repository entity types exist",()=>{const r=JSON.parse(fs.readFileSync(path.join(root,"source-registry.json")));for(const x of ["hosted_model_api","agent_skill","mcp","desktop_app","protocol"])assert.ok(r.entity_types.includes(x))});
test("non-empty run cannot bypass ledger",()=>{const o=structuredClone(base);o.tools=[{id:"x"}];assert.notEqual(run(o).status,0)});
test("Jev positive fixture is representable",()=>{const s=JSON.parse(fs.readFileSync(path.join(root,"schema.json")));const roles=s.$defs.source.properties.role.enum;for(const x of ["official_release","official_docs","official_sdk","official_skill"])assert.ok(roles.includes(x));assert.ok(s.$defs.tool.properties.entity_type.enum.includes("hosted_model_api"))});
test("hosted model contract requires official release and docs",()=>{const source=fs.readFileSync(validator,"utf8");assert.match(source,/hosted API needs official release/);assert.match(source,/hosted API needs official docs/)});
test("unconnected X is barred from succeeded",()=>assert.match(fs.readFileSync(validator,"utf8"),/unconnected X must be unavailable or failed/));
test("user nominations cannot silently disappear",()=>assert.match(fs.readFileSync(validator,"utf8"),/silently dropped/));
test("funnel must be recomputable",()=>assert.match(fs.readFileSync(validator,"utf8"),/funnel is not recomputable/));
test("discovery and publish audits are separate",()=>{const s=JSON.parse(fs.readFileSync(path.join(root,"schema.json")));assert.deepEqual(s.properties.run.properties.audits.required,["discovery","publish_gate"])});
test("canonical GitHub path rejects tails",()=>{const source=fs.readFileSync(validator,"utf8");assert.match(source,/noncanonical GitHub URL/);assert.match(source,/u\.pathname\.match/);assert.match(source,/v===`https:\/\/github\.com\/\$\{loc\}`/)});
test("npm path validation remains present",()=>assert.match(fs.readFileSync(validator,"utf8"),/noncanonical npm URL/));
test("fixed notices remain exact",()=>{const r=JSON.parse(fs.readFileSync(path.join(root,"source-registry.json")));assert.deepEqual(r.fixed_notices,["reliability_unverified","security_scan_not_run","review_source_before_use"])});
test("candidate state remains fixed",()=>assert.match(fs.readFileSync(validator,"utf8"),/candidate\/hold\/pending/));
test("GitHub signals bind to same repo",()=>assert.match(fs.readFileSync(validator,"utf8"),/GitHub signal not bound to same repo/));
test("coverage uses unique sources and exact family count",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/duplicate source attempts/);assert.match(s,/c\.families===attemptedFamilies\.size/)});
test("eligible entities bind to candidates",()=>assert.match(fs.readFileSync(validator,"utf8"),/eligible lead .* is missing from candidates/));
test("strict calendar dates reject normalization",()=>assert.match(fs.readFileSync(validator,"utf8"),/getUTCDate\(\)===d/));
test("raw signal definitions and types are enforced",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/unknown raw signal definition/);assert.match(s,/raw signal must be non-negative integer/)});
test("audit metadata validates digits dates and visible reviewers",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/\[a-z0-9_\]/);assert.match(s,/audit date invalid/);assert.match(s,/reviewerValid/)});
test("entity keys and discovery lists cannot be absent",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/invalid entity_key/);assert.match(s,/needs at least one discovery source/)});
test("attempt and check dates cannot exceed the run",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/bad\/future date/);assert.match(s,/t\.checked_at<=data\.run\.collected_at/)});
test("hosted APIs require release docs SDK and skill",()=>{const s=fs.readFileSync(validator,"utf8");for(const x of ["official_release","official_docs","official_sdk","official_skill"])assert.match(s,new RegExp(x))});
test("unknown fields are rejected at every publication layer",()=>assert.match(fs.readFileSync(validator,"utf8"),/has missing or unknown fields/));
test("discovery URLs need HTTPS and successful hits",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/discovery URL must be HTTPS/);assert.match(s,/a\.raw_hit_count>0/)});
test("lead priority is required and controlled",()=>assert.match(fs.readFileSync(validator,"utf8"),/has invalid priority/));
test("GitHub time signal uses strict UTC round trip",()=>assert.match(fs.readFileSync(validator,"utf8"),/d\.toISOString\(\)===normalized/));
test("lead decisions are unique per entity",()=>assert.match(fs.readFileSync(validator,"utf8"),/lead entity_key values must be unique/));
test("attempt and discovery enums are controlled",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/has invalid status/);assert.match(s,/discovery has invalid priority/);assert.match(s,/unconnected X must be unavailable or failed/)});
test("last push cannot postdate observation",()=>assert.match(fs.readFileSync(validator,"utf8"),/last-push cannot be after observation date/));
test("audit objects reject injected labels",()=>assert.match(fs.readFileSync(validator,"utf8"),/run\.audits\.discovery/));
test("audit front matter requires exactly five strict lines",()=>{const s=fs.readFileSync(validator,"utf8");assert.match(s,/lines\.length!==5/);assert.match(s,/pairs\.some\(x=>!x\)/)});
